service: ${file(package.json):name}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2
  memorySize: 128
  environment:
    JWT_SECRET: ${self:custom.secrets.jwtSecret}

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  secrets: ${file(config/secrets.json)}
  webpack:
    includeModules: true

package:
  individually: true

functions:
  get:
    handler: src/get-handler.get
    events:
      - http:
          path: /categories
          method: GET
